### ISSUE TITLE
QUIC interoperability

### ISSUE THREAD

**Issue by doublex** [webserver-llc/angie#100]
Picotls fails to process the initial QUIC packet from angie (via `proxy_http_version 3`).
This happens with any software that uses `picotls`, e.g. `h2o.examp1e.net`

In particular `picotls` complains about the CCS record, this line:
https://github.com/h2o/picotls/blob/master/lib/picotls.c#L1930

The `picotls` backtrace:
````c
push_change_cipher_spec()
server_handle_hello()
handle_server_handshake_message()
handle_handshake_record()
ptls_server_handle_message()
````

**Comment by vlhomutov** [comment]
Hello.

What SSL library are you using? I see that it really happens with compat mode using normal openssl. There are really interoperability issues  when using different SSL libraries on server and client (i.e. compat mode vs non-compat).

Can you please try to build with boringssl? It should be working.

**Comment by doublex** [comment]
You are right. We use `picotls` with `openssl` as SSL-backend.

**Comment by doublex** [comment]
@vlhomutov 
You are right. Everything works using `quictls`.
Sorry for the inconvenience.
