### ISSUE TITLE
SDN?

### ISSUE THREAD

**Issue by vanytsvetkov** [webserver-llc/angie#103]
[Forbes пишет, что Angie начал разрабатывать свой SDN контроллер](https://www.forbes.ru/tekhnologii/524090-metat-v-zamestiteli-bazis-i-angie-sozdadut-analog-popularnoj-platformy-ot-vmware), aka NSX. Есть вакансии для команды сетевых разработчиков из соседней строчки реестра по импортозамещению?

tg: @f1rs_t

**Comment by izaurio** [comment]
Есть, с удовольствием пообщаемся. Стучите мне напрямую @izaurio в телегу

**Comment by izaurio** [comment]
Вакансии есть, с удовольствие рассмотрим. В телегу напишу.
