### ISSUE TITLE
Debian пакеты под архитектуру arm64 (aarch64)

### ISSUE THREAD

**Issue by a2nt** [webserver-llc/angie#12]
Не хватает релиза под arm64 хотелось бы поставить Angie на Rockchip RK3588 вместо Nginx

**Comment by lonerr** [comment]
Уточните, пожалуйста, запрос.

В нашем репозитории имеются пакеты arm64 для buster и bullseye:
https://download.angie.software/angie/debian/pool/main/a/angie/

В инструкции по установке это, также, отражено:
https://angie.software/install/#debian

**Comment by a2nt** [comment]
Вот такую ошибку возвращает установка по инструкции:
`N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://download.angie.software/angie/ubuntu jammy InRelease' doesn't support architecture 'armhf'`

```
home:~:# dpkg --print-architecture
arm64
home:~:# uname -a
Linux home.local 5.10.110-rockchip-rk3588 #trunk.0196 SMP Wed Jan 25 03:01:40 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
home:~:# cat /etc/apt/sources.list.d/angie.list  
deb https://download.angie.software/angie/ubuntu/ jammy main
```

Но получилось установить прописав архитектуру:
`home:~:# apt install angie:arm64
`
