### ISSUE TITLE
потерялись образы

### ISSUE THREAD

**Issue by 21h** [webserver-llc/angie#16]
вроде образы помечены на сайте как опубликованные, а их нет

vlad@turtle:/$ docker pull docker.angie.software/angie:1.1.0-alpine
Error response from daemon: manifest for docker.angie.software/angie:1.1.0-alpine not found: manifest unknown: manifest unknown
vlad@turtle:/$ docker pull docker.angie.software/angie:1.1.0
Error response from daemon: manifest for docker.angie.software/angie:1.1.0 not found: manifest unknown: manifest unknown

мож нужна помощь с ci какая? )

**Comment by telkar** [comment]
Добрый день. 
О проблеме знаем, работаем.

**Comment by telkar** [comment]
Добрый день. 
Образы выложили, проверьте пожалуйста и сообщите о результате. 
Спасибо.

**Comment by 21h** [comment]
работает, огонь 🔥
