### ISSUE TITLE
Шаблоны файлов конфигурации

### ISSUE THREAD

**Issue by Tony-Sol** [webserver-llc/angie#17]
Официальный образ nginx поддерживает возможность шаблонизации файлов конфигурации, например для подстановки значений из переменных окружения (https://hub.docker.com/_/nginx см. Using environment variables in nginx configuration)

Есть ли альтернатива этому в Angie?

**Comment by Tony-Sol** [comment]
Своего рода workaround этого: 
https://github.com/Tony-Sol/docker/blob/master/images/angie/docker-entrypoint.d/10-envsubst-on-templates.sh

**Comment by lonerr** [comment]
Вы не могли рассказать подробнее про практический use-case этого решения?
Сделать не сложно, но хочется получше понять для чего.

**Comment by Tony-Sol** [comment]
Мой кейс, это локальная разработка - хочется иметь возможность динамически задавать server в upstream'е чтобы одной переменкой переключаться между например php-fpm и roadrunner'ом

**Comment by lonerr** [comment]
Но ведь вы для запуска контейнера, вероятно, монтируете внутрь свой кастомный конфиг (в котором есть placeholders для server в upstream). И, скорее всего, длинную команду `docker run ...` не запускаете каждый раз руками. Почему вам не нравится решение иметь несколько конфигов и монтировать внутрь нужный?

Поясню, что меня смущает. Подстановка скалярных переменных это вариант мини-шаблонизации. Он перестает работать сразу же, как возникает первая необходимость более серьезных отличий - появление нового `location`, `rewrite` или любой другой конфигурационной директивы. В этот момент, разделение конфигов становится практически неизбежным. Так почему бы не сделать это сразу и не мучаться с ограничениями подстановки переменных?

Возможно, я что-то недоучитываю - поправьте меня, пожалуйста.

**Comment by Tony-Sol** [comment]
> Но ведь вы для запуска контейнера, вероятно, монтируете внутрь свой кастомный конфиг (в котором есть placeholders для server в upstream).

Верно

> И, скорее всего, длинную команду docker run ... не запускаете каждый раз руками.

Верно, docker-compose это делает "за меня"

> Почему вам не нравится решение иметь несколько конфигов и монтировать внутрь нужный?

Не говорил что не нравится) Это действительно хорошая практика

> Подстановка скалярных переменных это вариант мини-шаблонизации. Он перестает работать сразу же, как возникает первая необходимость более серьезных отличий

Абсолютно верно, просто хочется иметь этот самый промежуточный вариант как раз для случаев когда можно обойтись 1й строкой в .env файле, а не дублировать конфиг. Эта возможность никак не заменяет собой подкладывание нужного конфига, а дополняет его.

**Comment by lonerr** [comment]
Мне кажется, что валидны два пути - использовать генератор конфигурации на основе шаблонов внутри образа и переменных окружения или полностью полагаться на конфигурацию смонтированную снаружи. Но вот гибридный вариант (монтируем, но потом еще и модифицируем) выглядит костыльно.
Пока не хотелось бы горячиться, впиливая подобное спорное решение.

**Comment by Tony-Sol** [comment]
согласен с @lonerr

**Comment by lonerr** [comment]
Тогда пока, если нет возражений, я закрою issue.
Если в какой-то момент станет актуальным - вернемся к этой теме.
