### ISSUE TITLE
Upstream dynamic DNS resolve in the stream module

### ISSUE THREAD

**Issue by vip-liutao** [webserver-llc/angie#28]
stream modules
Upstreams resolved when server starts, but i need to resolve upstream domain names asynchronously, it is possible for now?

**Comment by VBart** [comment]
Currently it's only possible for HTTP upstreams.

**Comment by VBart** [comment]
Implemented in Angie 1.3.0 for the "stream" module too: https://angie.software/en/stream_upstream/#server
