### ISSUE TITLE
jwt module

### ISSUE THREAD

**Issue by zil1** [webserver-llc/angie#29]
Добрый день.

Было бы очень круто, если бы добавили поддержку jwt модуля из коробки.
В данный момент мы самостоятельно собираем jwt модуль (https://github.com/max-lt/nginx-jwt-module), но это очень неудобно, т.к. после каждого обновления пакета Angie необходимо собирать модуль заново.

**Comment by telkar** [comment]
Добрый день. 

Не обещаю что сразу возьмёмся делать, но запрос записал. При портировании следующих модулей этот поставим первым.

**Comment by telkar** [comment]
Добрый день.

А подскажите пожалуйста, на каких ОС и их версиях у вас используется JWT модуль? 
Спасибо.

**Comment by zil1** [comment]
Добрый вечер.

Centos 7
3.10.0-1160.el7.x86_64

**Comment by telkar** [comment]
Спасибо. 

> Добрый вечер.
> 
> Centos 7 3.10.0-1160.el7.x86_64

**Comment by telkar** [comment]
Добрый день. 
Модуль собрали:
https://download.angie.software/angie/centos/7/x86_64/
Инструкция по настройке репозитория тут:
https://angie.software/install/#centos-oracle-red-os-rocky
