### ISSUE TITLE
Compilation instructions missing

### ISSUE THREAD

**Issue by jahway603** [webserver-llc/angie#3]
For those not running Ubuntu and Debian, can you please provide some basic compilation instructions so that we can help test on other distros of Linux?

**Comment by a2nt** [comment]
```
git clone https://github.com/webserver-llc/angie.git
cd angie
./configure
make
make install
```

**Comment by poluyanov** [comment]
Thank you @a2nt!

**Comment by VBart** [comment]
It's almost no different from nginx: http://nginx.org/en/docs/configure.html
