### ISSUE TITLE
angie 1.2.0 and modsecurity

### ISSUE THREAD

**Issue by emiliocamposmartin** [webserver-llc/angie#31]
HI, I have tried to compile angie with modsecurity as follow:

1-COmpile modsecurity 2.9.1 in standalone
2-Compile Angie 1.2.0 adding the module compiled in the configure  (--add-module=../modsecurity-2.9.1/nginx/modsecurity), in the make the following error is shown:

	/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c
/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c: In function ‘ngx_http_modsecurity_save_headers_in’:
/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c:358:39: error: ‘ngx_http_headers_in_t’ {aka ‘struct <anonymous>’} has no member named ‘cookies’; did you mean ‘cookie’?
     if (ngx_array_init(&r->headers_in.cookies, r->pool, 2,
                                       ^~~~~~~
                                       cookie
/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c: In function ‘ngx_http_modsecurity_save_request_body’:
/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c:531:17: error: ‘ngx_http_connection_t’ {aka ‘struct <anonymous>’} has no member named ‘nfree’; did you mean ‘free’?
         if (hc->nfree && size == cscf->large_client_header_buffers.size) {
                 ^~~~~
                 free
/opt/modsec/modsecurity-2.9.1/nginx/modsecurity//ngx_http_modsecurity.c:533:34: error: ‘ngx_http_connection_t’ {aka ‘struct <anonymous>’} has no member named ‘nfree’; did you mean ‘free’?
             buf = hc->free[--hc->nfree];
                                  ^~~~~
                                  free
make[1]: *** [objs/Makefile:1304: objs/addon/modsecurity/ngx_http_modsecurity.o] Error 1

Is mod security supported in Angie? I tried modsecurity version 2.9.1 maybe another version is required. 

Thanks!

**Comment by emiliocamposmartin** [comment]
Thanks for the prompt response, I will try as indicated.

Regards!

**Comment by VBart** [comment]
> Are there any plans to build the module similarly to the others?

^^ @lonerr

**Comment by lonerr** [comment]
@ihard, We've just released angie-module-modsecurity packages for all supported platforms:
https://angie.software/en/howto/modsecurity/

Please have a look and let us know how it helps.

**Comment by ihard** [comment]
works great, thanks!
