### ISSUE TITLE
how to setup more than one http3 server?

### ISSUE THREAD

**Issue by jonirrings** [webserver-llc/angie#34]
I've set two `server` by include a `conf`
```
listen 443 quic reuseport;
listen [::]:443 quic reuseport;
add_header Alt-Svc 'h3=":443"; ma=86400';
```
however, when I run `sudo angie -t`
it reports
```
angie: [emerg] duplicate listen options for 0.0.0.0:443 in /home/ubuntu/ssl/quic.conf:1
angie: configuration file /etc/angie/angie.conf test failed
```
do you guys got any guide to setup more than one http3 server?

**Comment by VBart** [comment]
Hi, please check the "listen" directive documentation: https://angie.software/en/http_core/#listen

The relevant quote: "_The listen directive can have several additional parameters specific to socket-related system calls. These parameters can be specified in any listen directive, but only once for a given address:port pair._"

You should set `reuseport` only once. Here is an example:
```nginx
server {
    listen       80;
    listen       443 ssl http2;
    listen       443 quic reuseport;
    server_name  example.org;

    add_header Alt-Svc 'h3=":443"; ma=86400';
}

server {
    listen       80;
    listen       443 ssl http2;
    listen       443 quic;
    server_name  example.com;

    add_header Alt-Svc 'h3=":443"; ma=86400';
}
```

**Comment by jonirrings** [comment]
great, it works, thx for your help.
