### ISSUE TITLE
RISCV64 support

### ISSUE THREAD

**Issue by jonirrings** [webserver-llc/angie#36]
Hi guys, 

I'm using angie from your deb repository on my rpi3b+(ubuntu, arm64), and it works great, specially for the http3.

And I want to use it on visionfive2 (ubuntu, riscv64)

Is there any plan to build a official riscv64 one?

**Comment by lonerr** [comment]
Hi,

It's a really good question :)
We had no such plan but now I've appended it to our future ideas list.
Thank you.

**Comment by jonirrings** [comment]
thank you very much
