### ISSUE TITLE
when did the nginx 1.25.1   will be merged in angie ?

### ISSUE THREAD

**Issue by yodatak** [webserver-llc/angie#38]
Thanks for your fork what is the policy about follow nginx mainline ? and when the nginx 1.25.1 will be merged 

There is some feature intersting 

    *) Feature: the "http2" directive, which enables HTTP/2 on a per-server
       basis; the "http2" parameter of the "listen" directive is now
       deprecated.

    *) Change: HTTP/2 server push support has been removed.

    *) Change: the deprecated "ssl" directive is not supported anymore.

    *) Bugfix: in HTTP/3 when using OpenSSL.

**Comment by VBart** [comment]
Angie 1.3 is planned for September with a number of interesting new features. It will merge nginx 1.25.2 (which I assume be ready by that time).

Btw, this one:
```
*) Bugfix: in HTTP/3 when using OpenSSL.  
```
is already part of Angie 1.2.0 release.

**Comment by VBart** [comment]
Currently, we make about 1 release per quarter, adding new features and merging the latest nginx version by that time.

**Comment by VBart** [comment]
nginx 1.25.2 has been merged recently: https://github.com/webserver-llc/angie/commit/8f00b01262c80592da9dd24ff80675aa90a55d97
