### ISSUE TITLE
Angie as an API gateway

### ISSUE THREAD

**Issue by madorin** [webserver-llc/angie#39]
Hello, Angie Developers!

Is it possible to use the Angie as an API gateway as Nginx Plus works, in terms of functionality?
I see Angie have JWT Auth module, location based upstream proxy, load balancing, etc...

Do Angie have a monitoring dashboard? 

Заранее спасибо!

**Comment by VBart** [comment]
Sure it's possible to use as an API gateway. With JWT and njs modules it can be configured to handle OIDC authentication.

We are currently working on a dashboard. I hope it will be ready by the next planned release in September.

Спасибо за проявленный интерес. =)

**Comment by madorin** [comment]
Thanks for feedback, @VBart !
I'll try to compile a Docker container using the needed modules.

Удачи Вам!
