### ISSUE TITLE
HTTP/3 Grace Termination

### ISSUE THREAD

**Issue by ammnt** [webserver-llc/angie#40]
Всем привет,

благодарю за вашу работу и отличный проект. Рассмотрите, пожалуйста, возможность добавления поддержки grace termination для протокола HTTP/3.

Спасибо!
Cheers✋🏼

**Comment by VBart** [comment]
Завершение соединений HTTP/3 в настоящий момент происходит согласно RFC с отправкой фрейма GOAWAY. Не могли бы вы раскрыть подробности, что вы подразумеваете под "HTTP/3 Grace Termination"?
