### ISSUE TITLE
HTTP/2 для бэкэнда в режиме реверс-прокси

### ISSUE THREAD

**Issue by ammnt** [webserver-llc/angie#41]
Всем привет,

благодарю за вашу работу и отличный проект. Очень не хватает протокола HTTP/2 для бэкэнда в режиме реверс-прокси. Пожалуйста, рассмотрите возможность его добавления.

Спасибо!
Cheers🤝

**Comment by VBart** [comment]
Расскажите пожалуйста подробнее о причинах по которым необходима поддержка данного протокола. Какую проблему такая поддержка должна решить.

**Comment by ammnt** [comment]
> Расскажите пожалуйста подробнее о причинах по которым необходима поддержка данного протокола. Какую проблему такая поддержка должна решить.

Не мудрствуя лукаво, скажу что реверс-проекс должен соответствовать современный стандартам и поддерживает функционал конкурентных решений (Traefik, Envoy и HAproxy), которые уже поддерживают HTTP/2 для бэкэнда, сколько известно.

Что касается преимуществ, то список будет всё тем же, что и список преимуществ протокола HTTP/2 перед HTTP/1.0😀

**Comment by VBart** [comment]
> > Расскажите пожалуйста подробнее о причинах по которым необходима поддержка данного протокола. Какую проблему такая поддержка должна решить.
> 
> Не мудрствуя лукаво, скажу что реверс-проекс должен соответствовать современный стандартам и поддерживает функционал конкурентных решений (Traefik, Envoy и HAproxy), которые уже поддерживают HTTP/2 для бэкэнда, сколько известно.
> 
> Что касается преимуществ, то список будет всё тем же, что и список преимуществ протокола HTTP/2 перед HTTP/1.0😀

Дело в том, что и список недостатков у HTTP/2 перед HTTP/1.1 будет тоже таким же. И если в случае браузер <-> веб-сервер приемущества HTTP/2 перевешивают недостатки, то в случае реверс-прокси <-> бекенд - всё с точностью наоборот.

Как разработчик одной из первых и самых популярных реализаций SPDY и HTTP/2 - я бы не рекомендовал использовать этот протокол для обмена данными между бекендом и реверс-прокси. По сравнинию с HTTP/1.1, перейдя на HTTP/2, вы получите меньшую пропускную способность за счет больших накладных расходов, а также дополнительно возможные проблемы с масштабированием на бекенде.

Единственный случай, когда HTTP/2 в сторону бекенда имеет смысл - это GRPC. Поддержка GRPC в Angie уже есть: https://angie.software/http_grpc/
