### ISSUE TITLE
Segmentation fault в случае вызова getenv функции из atexit колбека в модуле

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [webserver-llc/angie#42]
Минимальный пример с воспроизведение описан в https://github.com/dmitry-j-mikhin/angie-atexit-bug
Возникает только на  Angie 1.2.0, на ванильном Nginx 1.25.2 такой проблемы нет, выглядит регрессом самого Angie.

**Comment by VBart** [comment]
Вы сравниваете Angie 1.2.0, который базируется на nginx 1.25.0, с nginx 1.25.2. Если вы попробуете проделать то же самое с nginx 1.25.0, то получите точно такую же ошибку, поскольку она была исправлена в nginx данным коммитом: https://hg.nginx.org/nginx/rev/c209dc4eed17 - в версии 1.25.2.

Ошибка проявляется только при сборке с модулем HTTP/3.

Angie 1.3.0, который готовится к выходу, уже включает в себя данное исправление.

**Comment by dmitry-j-mikhin** [comment]
@VBart спасибо за наводку, да, на 1.25.0 та же проблема. Значит это не проблема Angie.
А не подскажете когда ждать 1.3.0? А патч версии типа 1.2.1 пока в Angie не планируются?

**Comment by dmitry-j-mikhin** [comment]
#42 тогда закрыл, т.к. действительно не связано с Angie.
> Ошибка проявляется только при сборке с модулем HTTP/3.

Чуть изменил тесты в https://github.com/dmitry-j-mikhin/angie-atexit-bug, проблема возникает именно в такой комбинации, когда в сборочной системе установлены linux-headers и включен флаг --with-http_v3_module. Если же собирать без linux-headers, хотя и со включенным --with-http_v3_module - то проблемы нет. В тестах это отразил.

**Comment by VBart** [comment]
> А не подскажете когда ждать 1.3.0? А патч версии типа 1.2.1 пока в Angie не планируются?

Где-то примерно недели через две. Выпускать 1.2.1 большого смысла не имеет, т.к. сильно критичных исправлений там не будет, а новая версия уже на подходе.
