### ISSUE TITLE
ROSA package

### ISSUE THREAD

**Issue by mikhailnov** [webserver-llc/angie#48]
Здравствуйте!
В репозитории Росы (ROSA Fresh, РОСА Хром, http://wiki.rosalab.ru/ru/index.php/Server_12.4) существует angie практически с момента его появления.
git со спецификацией сборки: https://abf.io/import/angie
Сборка последней версии: https://abf.io/build_lists/4751172 (сейчас на тестировании: https://bugzilla.rosalinux.ru/show_bug.cgi?id=13045)
Буду рад услышать какие-либо комментарии на счет опакечивания angie. Может быть, можно куда-нибудь в документацию добавить информацию о пакете в Росе.
Спасибо!

**Comment by lonerr** [comment]
Добрый день.
Мы поддерживаем репозитории пакетов Angie для ряда дистрибутивов, включая Rosa Linux: https://angie.software/install/#install-packages
Для каждого из них доступны source packages, например src rpm для Rosa: https://download.angie.software/angie/rosa/2021.1/source/
Думаю будет полезно сравнить общее и разное в подходах и в каких-то местах придти к общему знаменателю.
Спасибо, что поделились информацией.

**Comment by mikhailnov** [comment]
Не вижу Росы по первой ссылке, а вторая ведет в 404...

**Comment by lonerr** [comment]
Да, извиняюсь, дело в том, что пакеты для Rosa мы выложили буквально несколько дней назад, поэтому в документацию на сайт это еще не успело попасть. Но вторую ссылку я поправил, проверяйте.

**Comment by mikhailnov** [comment]
Очень круто! В целом сборки похожи, в т.ч. подход к упаковке модулей почти одинаковый. Я у вас, наверное, позаимствую список сторонних модулей.

С nodebug и debug вариантами в одном пакете интересно.

Вижу такую проблему: в вашем репозитории и в репозитории Росы получаются одноименные пакеты с модулями, например, angie-module-brotli. Release пакета в Росе может оказаться выше, а привязка "Requires: angie = %{version}-%{release}" может не сработать должным образом, т.к. сам пакет angie тоже одноименный и есть и там и там. В предлагаемых вами конфигах dnf (https://angie.software/install/#install-yum) нет настройки приоритета репозиториев.
Можно у вас просто к Release добавить букву (-ы), то есть не 2, а, допустим, 2ang, тогда вроде все проблемы решатся.

У вас зависимость от systemd, но где-то используется systemctl, а где-то service, мне кажется, стоит переделать везде на systemctl (systemctl reload angie вызывает ExecReload)

**Comment by mikhailnov** [comment]
Помимо релиза, стоит все же задать приоритет репозитория < 100, см. priority в man dnf.conf, думаю, а то иначе установленные из одного репозитория пакеты смогут обновиться до пакетов из другого репозитория, если не установлено модулей, которые есть только в одном репозитории.

**Comment by lonerr** [comment]
> Очень круто! В целом сборки похожи, в т.ч. подход к упаковке модулей почти одинаковый. Я у вас, наверное, позаимствую список сторонних модулей.
> 
> С nodebug и debug вариантами в одном пакете интересно.
> 
> Вижу такую проблему: в вашем репозитории и в репозитории Росы получаются одноименные пакеты с модулями, например, angie-module-brotli. Release пакета в Росе может оказаться выше, а привязка "Requires: angie = %{version}-%{release}" может не сработать должным образом, т.к. сам пакет angie тоже одноименный и есть и там и там. В предлагаемых вами конфигах dnf (https://angie.software/install/#install-yum) нет настройки приоритета репозиториев. Можно у вас просто к Release добавить букву (-ы), то есть не 2, а, допустим, 2ang, тогда вроде все проблемы решатся.
> 
> У вас зависимость от systemd, но где-то используется systemctl, а где-то service, мне кажется, стоит переделать везде на systemctl (systemctl reload angie вызывает ExecReload)

**Comment by mikhailnov** [comment]
> Кажется, в таком случае можно не добавлять суффикс в Release.

В целом да, но, если version-release пакета angie из разных репозиториев совпадет, то пакет angie-module-X из одного репозитория сможет встать рядом с angie из другого репозитория, когда как совместимость ABI, наверное, все же не гарантирована.

Также может оказаться так, что ваш репозиторий подключат, когда уже стоит angie из репозитория Росы, а потом начнут ставить от вас модули.

Но в целом согласен, что большой необходимости в суффиксе нет.

Про upgrade понял. Он у вас вызывается в %postun, то есть при обновлении пакета его вызовет postun старого пакета (https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering), а значит, если решите отказаться от service upgrade, то при обновлении получится ошибка. Тогда добавили бы "Requires(postun): /sbin/service", а то пакета с /sbin/service может и не оказаться в системе, хоть он пока что есть из коробки.

**Comment by mikhailnov** [comment]
>  другого способа вызвать custom action в systemd попросту нет.

Кажется, то, что делает этот скрипт, можно делать и без service, а service просто для универсальности между платформами получается.

**Comment by lonerr** [comment]
Приоритет (`priority=9`) мы добавили в инструкцию: https://angie.software/install/#install-yum

Что касается `service angie upgrade` - да, нам хотелось бы иметь единообразный механизм управления, для консистентного предоставления информации на сайте. Таким механизмом видится `service`, а не `systemctl`.

Добавить `Requires: /sbin/service` в спеку можно, но автоматически возникает вопрос - в наличии еще каких утилит, используемых  на фазах `pre/post/etc.` мы не можем быть гарантированно уверены? (`getent, groupadd, useradd, touch, chmod, chown`, etc.)

**Comment by mikhailnov** [comment]
Строго говоря, вы не можете быть уверены в наличии ни одной из этих утилит, потому что, если собирать ISO-образ (например, с помощью https://abf.io/soft/rosa-build-iso) или chroot/rootfs (образ контейнера) с предустановленным angie, то все пакеты, даже если их несколько тысяч, ставятся одной транзакцией. Если не указано, что на момент выполнения скриптлета нужен какой-то пакет, то пакет angie может начать ставиться, когда в системе еще нет нужной утилиты.

**Comment by mikhailnov** [comment]
В инструкции написано "ROSA Fresh", но на той же пакетной базе еще есть Роса Хром (ROSA Chrome) - корпоративная версия по сути дела того же дистрибутива, может, можно ее упомянуть

**Comment by mikhailnov** [comment]
Еще yum все же устаревший механизм, пакетный менеджер dnf, yum лишь симлинк на dnf. Пользователей Росы изначально учат в документации, на вики и т.д. использовать dnf, слово yum может смутить тех, кто не в курсе, что это то же самое.

**Comment by lonerr** [comment]
> Еще yum все же устаревший механизм, пакетный менеджер dnf, yum лишь симлинк на dnf. Пользователей Росы изначально учат в документации, на вики и т.д. использовать dnf, слово yum может смутить тех, кто не в курсе, что это то же самое.

Это сделано в целях унификации инструкции. К примеру, в этом же блоке у нас CentOS 7, а dnf по умолчанию на ней отсутствует.

**Comment by os-killer** [comment]
> В инструкции написано "ROSA Fresh", но на той же пакетной базе еще есть Роса Хром (ROSA Chrome) - корпоративная версия по сути дела того же дистрибутива, может, можно ее упомянуть

Дело в том, что на данный момент, мы не являемся технологическими партнерами ООО «НТЦ ИТ РОСА». Мы не собирали и не тестировали Angie под коммерческую версию ОС РОСА Хром. Соответственно, гарантировать 100% работоспособность нашего продукта на данной ОС мы не можем. В нашей документации мы указываем только те операционные системы на которых проводились функциональные тесты. И по этой причине, в нашей инструкции, мы не заявляли ОС РОСА Хром как доступную для установки.

**Comment by Gibadm2** [comment]
Коллеги, добрый день!

Давайте исправим эту ситуацию!
Я отвечаю за технический стек отдела Технологического партнерства. По данному направлению я помогу официально оформить наши взаимоотношения.

> > В инструкции написано "ROSA Fresh", но на той же пакетной базе еще есть Роса Хром (ROSA Chrome) - корпоративная версия по сути дела того же дистрибутива, может, можно ее упомянуть
> 
> Дело в том, что на данный момент, мы не являемся технологическими партнерами ООО «НТЦ ИТ РОСА». Мы не собирали и не тестировали Angie под коммерческую версию ОС РОСА Хром. Соответственно, гарантировать 100% работоспособность нашего продукта на данной ОС мы не можем. В нашей документации мы указываем только те операционные системы на которых проводились функциональные тесты. И по этой причине, в нашей инструкции, мы не заявляли ОС РОСА Хром как доступную для установки.

**Comment by os-killer** [comment]
> Коллеги, добрый день!
> 
> Давайте исправим эту ситуацию! Я отвечаю за технический стек отдела Технологического партнерства. По данному направлению я помогу официально оформить наши взаимоотношения. Для этого мне нужно получить контакты для связи.
> 
> > > В инструкции написано "ROSA Fresh", но на той же пакетной базе еще есть Роса Хром (ROSA Chrome) - корпоративная версия по сути дела того же дистрибутива, может, можно ее упомянуть
> > 
> > 
> > Дело в том, что на данный момент, мы не являемся технологическими партнерами ООО «НТЦ ИТ РОСА». Мы не собирали и не тестировали Angie под коммерческую версию ОС РОСА Хром. Соответственно, гарантировать 100% работоспособность нашего продукта на данной ОС мы не можем. В нашей документации мы указываем только те операционные системы на которых проводились функциональные тесты. И по этой причине, в нашей инструкции, мы не заявляли ОС РОСА Хром как доступную для установки.

Добрый день! Напишите, пожалуйста, нам на info@wbsrv.ru. Ответственные люди уже в курсе и подхватят.

**Comment by mikhailnov** [comment]
Коллеги, смотрю, вы делаете отдельные сборки для Росы Хром (https://download.angie.software/angie/rosa-chrome/2021.1/x86_64/) и Росы Фреш (https://download.angie.software/angie/rosa/2021.1/x86_64/), но ведь они построены на базе одного и того же репозитория rosa2021.1, то есть технического смысла делать отдельные сборки в данный момент, на платформе rosa2021.1, думаю, нет. Это относится и к архитектуре aarch64. Это осознанное решение?) Просто на всякий случай написал.

**Comment by mikhailnov** [comment]
Или, может, это такой задел на будущее, если Фреш и Хром разделятся? Выпуск Фреша 12.5 по плану последний, далее на платформе rosa2021.1 будет выпускаться только Хром, а Фреш уже на новой платформе 2023.1 (или, может быть, она будет переименована). Но в любом случае пакеты же собираются не под Фреш, Хром, МОС или что-то еще, построенное на базе платформы, а под платформу, как программное окружение, не должно быть такой ситуации, что на базе одной платформы выпускаются дистрибутивы с разным программным окружением.

**Comment by lonerr** [comment]
По своей сути, это вопрос схемы именования наших репозиториев ("Фреш"/"Роса" vs "2021.1"/"2023.1").
Если я вам понял правильно, то вы предлагаете нам использовать вторую схему.
На мой взгляд - звучит вполне резонно, обязательно обсудим с коллегами, спасибо.

**Comment by mikhailnov** [comment]
Сейчас вот есть Фреш на 2016.1 и на 2021.1, скоро появится на и на 2023.1. Хром на 2016.1 назывался ROSA Eneterprise Desktop (RED) X4. Потом будут существовать одновременно Хром на 2021. 1 и Хром на 2023.1. 
В инструкциях по установке у вас используется переменная $releasever, которая раскрывается в платформу, 2021.1 или 2023.1, этого в целом достаточно, мне кажется, чтобы упростить инструкцию до просто "Роса".
Но нще есть rosa2021.15 - форк rosa2021.1, но сертифицированный ФСТЭК. Хром ФСТЭК А4 находится на завершающих этапах сертификации и построен на базе 2021.15. Сейчас это фактически копия 2021.1 с запаздыванием, но неизвестно, как будет дальше.
Если на 2021.15 пользователь выполнит предлагаемые в инструкции действия,  то $releasever примет такое значение, что получится ошибка 404.
Можно собирать под 2021.15 отдельно, можно, наверное, сделать в репозитории симлине rosa2021.1 -> rosa2021.15, в данный момент этого будет достаточно, а дальше - не знаю, поживем - увидим.
Вчера посмотрел, от каких библиотек зависят модули angie, например, angie-module-modsecurity, а там такие редкие библиотеки (то есть такие, у которых в репозитории Росы мало потребителей), что при необходимости, например, исправить уязвимость, может быть принято обновить с изменением soname и пересборкой потребителей в репозитории, тогда ваши пакеты отвалятся. Не знаю, как тут лучше поступить, в идеале бы их статически линковать, например, если надо, мы можем попробовать сделать статические версии в репозитории.

**Comment by lonerr** [comment]
Мы посовещались и пришли к мнению, что будет проще и безопаснее оставить разделение наших репозиториев по версиям предоставляемых вами дистрибутивов (даже если они используют общую пакетную базу). Это дает нам уверенность в применимости пакета на целевой системе, даже если пакетные базы в какой-то момент начнут различаться.
Накладные расходы на одну лишнюю сборку и ее хранение нас смущают значительно меньше, чем риск возможных проблем на стороне пользователей.

**Comment by mikhailnov** [comment]
Хорошо, спасибо)
