### ISSUE TITLE
[Feature] nginx-opentracing в составе angie

### ISSUE THREAD

**Issue by patsevanton** [webserver-llc/angie#49]
Здравствуйте. Спасибо за angie!
Было бы классно увидеть модуль nginx-opentracing включенный в состав angie.
Либо ваша реализация tracing.

**Comment by telkar** [comment]
Добрый вечер.
Спасибо, рады стараться.
Подскажите пожалуйста, с каким плагином Вы планируете использовать модуль opentracing?

**Comment by patsevanton** [comment]
https://github.com/opentracing-contrib/nginx-opentracing
но пока не пользуемся. В беклоге

**Comment by telkar** [comment]
Добрый день, модуль nginx-opentracing собрали. Репозитории выкатили. 
В модуле также присутствуют плагины для DataDog и Zipkin.
Будем благодарны за отзыв.

**Comment by patsevanton** [comment]
@telkar В обычном docker образе будет angie с модулем nginx-opentracing ?

**Comment by telkar** [comment]
Добрый вечер. 
Обновил Docker образы. Теперь в них есть модуль nginx-opentracing.

**Comment by lonerr** [comment]
> Добрый день. Подскажите, пожалуйста, почему для opentelemetry был выбран модуль https://github.com/opentracing-contrib/nginx-opentracing

Потому что данное issue открыто именно как запрос на этот модуль )
Но opentelemetry у нас также в ближайших планах.

**Comment by dolgovas** [comment]
![image](https://github.com/webserver-llc/angie/assets/43605609/73507f65-c8db-4f6a-a991-8370b056e6b0)
Понял, спасибо за ответ

**Comment by agolodyaev** [comment]
Коллеги, спасибо за angie!
А можно вот такое https://docs.nginx.com/nginx/admin-guide/dynamic-modules/opentelemetry/ и  для RH-based дистрибутивов?

**Comment by telkar** [comment]
Добрый день, @agolodyaev.
Этот модуль есть в списке на добавление в репозитории. Точных сроков не смогу назвать, но мы работаем в этом направлении.

**Comment by Ligature60** [comment]
Добрый день.
Модуль angie-module-otel включен в репозитория с релизом [1.5.0](https://github.com/webserver-llc/angie/releases/tag/Angie-1.5.0)

**Comment by patsevanton** [comment]
angie-module-otel это модуль opentelemetry ?

**Comment by Ligature60** [comment]
Да, это модуль https://github.com/nginxinc/nginx-otel

**Comment by agolodyaev** [comment]
> Добрый день. Модуль angie-module-otel включен в репозитория с релизом [1.5.0](https://github.com/webserver-llc/angie/releases/tag/Angie-1.5.0)

Коллеги, большое спасибо!
