### ISSUE TITLE
angie -V and   nginx -V: different results

### ISSUE THREAD

**Issue by nobicycle** [webserver-llc/angie#5]
Thank you for Angie. The problem is below:
```
user@tower ~]$ angie -V
Angie version: Angie/1.0.0
built by gcc 12.2.0 (GCC) 
configure arguments:

[user@tower ~]$ nginx -V
nginx version: nginx/1.22.1
built with OpenSSL 1.1.1q  5 Jul 2022
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/bin/nginx --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --user=http --group=http --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto' --with-ld-opt='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads

```

**Comment by VBart** [comment]
Which configure arguments have you specified while building Angie from sources?

**Comment by nobicycle** [comment]
Hello VBart

NGX_PREFIX=/etc/angie
NGX_SBIN_PATH=/usr/sbin/angie
NGX_MODULES_PATH=/usr/lib/angie/modules
NGX_CONF_PATH=/etc/angie/angie.conf
NGX_ERROR_LOG_PATH=/var/log/angie/error.log
NGX_PID_PATH=/var/run/angie.pid
NGX_LOCK_PATH=/var/run/angie.lock
NGX_USER=http
NGX_GROUP=http

**Comment by VBart** [comment]
> Hello VBart
> 
> NGX_PREFIX=/etc/angie NGX_SBIN_PATH=/usr/sbin/angie NGX_MODULES_PATH=/usr/lib/angie/modules NGX_CONF_PATH=/etc/angie/angie.conf NGX_ERROR_LOG_PATH=/var/log/angie/error.log NGX_PID_PATH=/var/run/angie.pid NGX_LOCK_PATH=/var/run/angie.lock NGX_USER=http NGX_GROUP=http

How do you run `./configure` script?

The `nginx -V` and `angie -V` outputs show exactly the same information. The reason why in your case outputs are so different is that nginx and Angie were built with different `./configure` arguments.

nginx in your case was configured with the following command:
```
./configure --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/bin/nginx --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --user=http --group=http --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto' --with-ld-opt='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads
```

If you configure Angie with the same arguments, you will get similar `angie -V` output. I run the command above on Angie sources and got:
```
% angie -V
Angie version: Angie/1.0.0
built by gcc 9.3.0 (Gentoo 9.3.0 p1) 
built with OpenSSL 1.1.1i  8 Dec 2020
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --conf-path=/etc/nginx/nginx.conf --sbin-path=/usr/bin/nginx --pid-path=/run/nginx.pid --lock-path=/run/lock/nginx.lock --user=http --group=http --http-log-path=/var/log/nginx/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/nginx/client-body --http-proxy-temp-path=/var/lib/nginx/proxy --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto' --with-ld-opt='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads
```
It almost identical to your `nginx -V` output with the only difference in GCC and OpenSSL versions installed on my system.

**Comment by nobicycle** [comment]
> How do you run `./configure` script?

	./configure && 	make

[options.txt](https://github.com/webserver-llc/angie/files/9989491/options.txt)


I  reran my script ad it showed:

Configuration summary
  + using system PCRE2 library
  + OpenSSL library is not used
  + using system zlib library
```

  Angie path prefix: "/etc/angie"
  Angie binary file: "/usr/sbin/angie"
  Angie modules path: "/usr/lib/angie/modules"
  Angie configuration prefix: "/etc/angie"
  Angie configuration file: "/etc/angie/angie.conf"
  Angie pid file: "/var/run/angie.pid"
  Angie error log file: "/var/log/angie/error.log"
  Angie http access log file: "/etc/angie/logs/access.log"
  Angie http client request body temporary files: "client_body_temp"
  Angie http proxy temporary files: "proxy_temp"
  Angie http fastcgi temporary files: "fastcgi_temp"
  Angie http uwsgi temporary files: "uwsgi_temp"
  Angie http scgi temporary files: "scgi_temp"
```
I edited the script with your config command format:

`	./configure --prefix=/etc/angie --conf-path=/etc/angie/angie.conf --sbin-path=/usr/bin/angie --pid-path=/run/angie.pid --lock-path=/run/lock/angie.lock --user=http --group=http --http-log-path=/var/log/angie/access.log --error-log-path=stderr --http-client-body-temp-path=/var/lib/angie/client-body --http-proxy-temp-path=/var/lib/angie/proxy --http-fastcgi-temp-path=/var/lib/angie/fastcgi --http-scgi-temp-path=/var/lib/angie/scgi --http-uwsgi-temp-path=/var/lib/angie/uwsgi --with-cc-opt='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto' --with-ld-opt='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' --with-compat --with-debug --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-pcre-jit --with-stream --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads && make
`
systemd reported at start:
2022/11/11 18:25:07 [emerg] 79292#79292: mkdir() "/var/lib/angie/client-body" failed (2: No such file or directory)

I am still not sure which auto/options are wrong or need editing. Those I listed above  are what Angie documentation  specifies. They seem right for Arch  Linux

**Comment by VBart** [comment]
> 2022/11/11 18:25:07 [emerg] 79292#79292: mkdir() "/var/lib/angie/client-body" failed (2: No such file or directory)

Do you actually have `/var/lib/angie` directory on your system?
You have specified it as intermediate directory in many options:
```
 --http-client-body-temp-path=/var/lib/angie/client-body --http-proxy-temp-path=/var/lib/angie/proxy --http-fastcgi-temp-path=/var/lib/angie/fastcgi --http-scgi-temp-path=/var/lib/angie/scgi --http-uwsgi-temp-path=/var/lib/angie/uwsgi
 ```
 Both nginx and Angie expect all configured intermediate directories are exist.

**Comment by VBart** [comment]
> I am still not sure which auto/options are wrong or need editing. 

This file isn't supposed to be edited at all. All parameters must be specified via `./configure` script arguments and `./configure --help` shows all of them.

**Comment by nobicycle** [comment]
I created that directory. Problem was the fixed.
Many thanks
