### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by autokilla47** [webserver-llc/angie#50]
Are you planning to create a Grafana dashboard?

**Comment by os-killer** [comment]
> Are you planning to create a Grafana dashboard?

No, we have no such plans.

**Comment by os-killer** [comment]
> Are you planning to create a Grafana dashboard?

Are you talking about dashboards like for NGINX Plus? For example:
https://grafana.com/grafana/dashboards/19314-nginx-plus-dashboard/
or Ingress:
https://github.com/kubernetes/ingress-nginx/tree/main/deploy/grafana/dashboards#grafana-dashboards

**Comment by autokilla47** [comment]
> > Are you planning to create a Grafana dashboard?
> 
> Are you talking about dashboards like for NGINX Plus? For example: https://grafana.com/grafana/dashboards/19314-nginx-plus-dashboard/ or Ingress: https://github.com/kubernetes/ingress-nginx/tree/main/deploy/grafana/dashboards#grafana-dashboards

In my opinion something like https://grafana.com/grafana/dashboards/19314-nginx-plus-dashboard/ will be grade.

**Comment by os-killer** [comment]
> > > Are you planning to create a Grafana dashboard?
> > 
> > 
> > Are you talking about dashboards like for NGINX Plus? For example: https://grafana.com/grafana/dashboards/19314-nginx-plus-dashboard/ or Ingress: https://github.com/kubernetes/ingress-nginx/tree/main/deploy/grafana/dashboards#grafana-dashboards
> 
> In my opinion something like https://grafana.com/grafana/dashboards/19314-nginx-plus-dashboard/ will be grade.

We will consider this for sure, thanks for idea ;)

**Comment by VBart** [comment]
Hi, we've created a Grafana dashboard. You're welcome to try: https://grafana.com/grafana/dashboards/20719-angie-dashboard/
