### ISSUE TITLE
angie:1.3.1-rocky docker running error

### ISSUE THREAD

**Issue by rongfengliang** [webserver-llc/angie#54]
when I  running angie with docker (using  docker.angie.software/angie:1.3.1-rocky  ) some error message 

```code
angie: [emerg] open() "/run/angie/angie.pid" failed (2: No such file or directory)
```

**Comment by telkar** [comment]
Hello,

Thanks for pointing to the issue.
We have already fix it. 
Could you please try one more time and let us know how it works for you.

**Comment by rongfengliang** [comment]
@telkar  Yes, it works
