### ISSUE TITLE
provide build-in module version

### ISSUE THREAD

**Issue by rongfengliang** [webserver-llc/angie#55]
Currently, we can us some build-in nginx modules in  OS pacakges  and docker images  . but don't known which nginx module it use
maybe provide some module version  docs for better to  write  nginx directives (diffrent nginx  module maybe provide diffrent directives )

**Comment by VBart** [comment]
@rongfengliang please see here: https://angie.software/en/install/#install-dynamicmodules - for links to all the modules we provide in packages with Angie

**Comment by rongfengliang** [comment]
@VBart Thanks, I have see this links . maybe provide some information  version information about  thirdpart modules maybe better

**Comment by telkar** [comment]
Hello @rongfengliang ,
Thanks for the good idea.
We are going to think about best approach of adding an original module version into each package.

**Comment by telkar** [comment]
Hello @rongfengliang ,
We have added the README file into each module package which contains information about its sources.
The below is the example location of that file within brotli module package:
/usr/share/doc/angie-module-brotli/README
