### ISSUE TITLE
[Feature] nginx-auth-ldap module

### ISSUE THREAD

**Issue by trombonax** [webserver-llc/angie#59]
Добрый день.
Вижу, что вы собираете бинарные пакеты для большинства сторонних востребованных модулей, это отличный подход, спасибо.

Если возможно, рассмотрите, пожалуйста, включение в список собираемых бинарных пакетов очень полезный модуль nginx-auth-ldap

https://github.com/kvspb/nginx-auth-ldap

Я проверил сборку и работу этого модуля из master ветки с версией angie-1.3.2

**Comment by lonerr** [comment]
Добрый день.
Да, спасибо за идею, добавим.

**Comment by Ligature60** [comment]
Добрый день.
Сегодня вышел Angie 1.4.0, в официальный репозиторий включен пакет модуля auth-ldap: https://angie.software/a_changes/#id2

**Comment by trombonax** [comment]
Отличная новость, спасибо.
