### ISSUE TITLE
image_filter and convertation in webp

### ISSUE THREAD

**Issue by okpoxa** [webserver-llc/angie#6]
Hi

A good feature for the module image_filter would be the ability to change the format of the resulting image, otherwise it is now issued in the same format as the original image. And converting to the webp format is quite a promising activity.

**Comment by poluyanov** [comment]
Hi, @okpoxa 
I prepared a patch for it, so you can be beta tester.

**Comment by okpoxa** [comment]
Yes, i am ready.

**Comment by poluyanov** [comment]
@okpoxa Please, provide your email

**Comment by okpoxa** [comment]
kpoxa kpoxa.net

**Comment by okpoxa** [comment]
@poluyanov

**Comment by okpoxa** [comment]
@poluyanov , send me patch.

**Comment by poluyanov** [comment]
@okpoxa done! I close the issue. If you have any questions, please write me via email.
