### ISSUE TITLE
mod_zip module

### ISSUE THREAD

**Issue by zil1** [webserver-llc/angie#64]
Добрый день.
Если возможно, рассмотрите, пожалуйста, включение в список собираемых бинарных пакетов модуль mod_zip (https://github.com/evanmiller/mod_zip)

**Comment by lonerr** [comment]
Здравствуйте.
Спасибо за идею, обязательно посмотрим.

**Comment by Ligature60** [comment]
Добрый день
Модуль mod_zip включен в репозиторий Angie как angie-module-zip.
