### ISSUE TITLE
Скрипт сборки динамических модулей pkg-oss

### ISSUE THREAD

**Issue by nwhisper2014** [webserver-llc/angie#65]
Здравствуйте!

Для nginx есть специальный скрипт для сборки динамических модулей [pkg-oss](https://hg.nginx.org/pkg-oss/). С помощью этого скрипта получается легко автоматизировать процесс сборки модулей и модули все соответствуют единому стилю.

Скажите, пожалуйста, есть ли аналог или похожая альтернатива для angie?

**Comment by lonerr** [comment]
Добрый день.
Вероятно, речь идет о `build_module.sh` от Liam Crilly из указанного репозитория?
Если я правильно понял, то - нет, подобного генератора мы не используем.
