### ISSUE TITLE
Добавить поддержку lua в модуль angie-module-modsecurity

### ISSUE THREAD

**Issue by dvmalygin** [webserver-llc/angie#69]
Просьба добавить поддержку lua в динамический модуль angie-module-modsecurity.
При использовании в правилах modsecurity действия exec - появляется ошибка:
`angie: [emerg] "modsecurity_rules_file" directive Rules error. exec: Lua support was not enabled.`

**Comment by Ligature60** [comment]
Добрый день.
Спасибо за предложение, мы подумаем над ним. Не могли бы вы, пожалуйста, подробнее описать ваш usecase?

**Comment by dvmalygin** [comment]
Добрый день!
Начиная с 3 версии modsecuruty в exec можно указывать только скрипты lua. 
Использовать скрипт в правилах modsecurity хотим для реализации механизма записи (сохранения) ip адресов, от которых были атаки, например, типа SQLI (SQL Injection), в файл для последующей их постоянной блокировки и отправки уведомления.
Т.е. по умолчанию modsecurity блокирует SQL Injection на уровне сессии, но после этого с этого же ip адреса можно продолжать слать другие запросы. Мы хотим блокировать такие адреса полностью с помощью отдельного правила modsecurity, считывающего адреса из файла.

**Comment by Ligature60** [comment]
Спасибо за информацию

**Comment by Ligature60** [comment]
Добрый день.
Поддержка Lua в модуле angie-module-modsecurity добавлена с релизом [1.5.0](https://github.com/webserver-llc/angie/releases/tag/Angie-1.5.0)
