### ISSUE TITLE
Debianization and build package error

### ISSUE THREAD

**Issue by NickyX3** [webserver-llc/angie#7]
Привет, а можно в релиз еще и архив дебианизации выкладывать? Аналогично nginx'овскому `.debian.tar.xz`
Всеж 2022 год на дворе, многие свои пакеты собирают и свои репозитории держат

**Comment by NickyX3** [comment]
Я как бы нашел в репе, но в релизах было бы удобнее, чтоб не рыться в репозитории

**Comment by lonerr** [comment]
Добрый день.

Судя по-всему, под "дебианизацией" вы понимаете source package.
Если так, то мы его предоставляем в нашем репозитории, рекомендованный способ получения и самостоятельной пересборки выглядит так:

    sudo apt install -y ca-certificates curl lsb-release
    sudo curl -o /etc/apt/trusted.gpg.d/angie-signing.gpg https://angie.software/keys/angie-signing.gpg
    echo "deb-src https://download.angie.software/angie/debian/ `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/angie.list >/dev/null
    sudo apt update
    sudo apt install -y devscripts dh-make
    sudo apt install -y expect libedit-dev libgeoip-dev libmaxminddb-dev libpcre2-dev libssl-dev mmv zlib1g-dev
    apt source angie
    cd angie-1.0.0
    debuild -uc -us


Спасибо за то, что обратили наше внимание на ошибку, имевшуюся  в этом пакете.
Исправленная версия уже загружена в репозиторий, попробуйте обновить индекс и повторить сборку.

**Comment by NickyX3** [comment]
Под дебианизацией я понимаю тот архив с папкой debian и rules для сборки аналогично nginx, куда я накину ещй свой набор модулей и правила для сборки не только пакета с сервером, а еще и пакетов с модулями.
В идеале бы вообще хотелось вкинуть rules от nginx и все :-)

**Comment by lonerr** [comment]
Мы сейчас как раз занимаемся адаптацией сборки наиболее популярных модулей от nginx. В самое ближайшее время они также будут доступны в нашем репозитории.
Можете перечислить интересные вам? Постараемся добавить в наш список, если их там еще нет.
Спасибо.

**Comment by NickyX3** [comment]
О! Наш список такой. В порядке нужности
Особо важные
https://github.com/alibaba/nginx-http-concat - склейка js/css в один запрос
https://github.com/arut/nginx-let-module - простые вычисления, в основном для image_filter
https://www.nginx.com/resources/wiki/modules/redis/ - redis старый, умеет отдавать из ключа
https://github.com/openresty/redis2-nginx-module - redis2, он уже умеет и класть в ключ что-то
Не сильно важные
https://github.com/openresty/headers-more-nginx-module
https://github.com/openresty/set-misc-nginx-module

**Comment by lonerr** [comment]
Принято, включим в список для рассмотрения.

**Comment by lonerr** [comment]
Наиболее актуальные модули из списка выше мы добавили.
На этом закрываю issue, спасибо.
