### ISSUE TITLE
Idea: combining with free nginx

### ISSUE THREAD

**Issue by melroy89** [webserver-llc/angie#74]
Just some idea / brainstorm. Since free nginx was also recently created by another core developer.

Would it not be a good idea to combine the time & effort? I mean, I see a lot of overlap.

I personally don't know how good the relationship is between these two projects. But please consider it since I believe we more or less want to achieve the same together: a free and good nginx replacement.

**Comment by VBart** [comment]
Hi. We are definitely looking for cooperation. As soon there will be valuable changes in freenginx we'll be happy to integrate them in Angie as well.

But there actually not so many overlap. Having a lot of experience with Maxim in the past, I'd rather say that we have quite different views of nginx future. And I dare say, under his control there wouldn't be a half of features that Angie currently provides over nginx. Note that for the last 10+ years nginx was under almost full control of Maxim, and the current shape of nginx, like it or not, mostly obligates to his views.

**Comment by melroy89** [comment]
Would it not be cool if you list some of those most important extensions that Angie delivers which isn't part of nginx/free and nginx on your Readme?

**Comment by melroy89** [comment]
Thanks for giving me more insides and answering my questions. I will close it for now.
