### ISSUE TITLE
The console.angie monitoring tool cannot display HTTP upstream information.

### ISSUE THREAD

**Issue by jointigers** [webserver-llc/angie#77]
I want to view HTTP upstream information, but I can't see it after deployment. I saw it in the demo.

![1711518314741](https://github.com/webserver-llc/angie/assets/19964667/16221e3d-2749-4e27-b355-cd40ba8e5da5)

    server {
        listen       8080;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }
        location /console/ {
            allow all;

            alias /usr/share/angie-console-light/html/;
            index index.html;

        location /console/api/ {
                 allow all;
                api /status/;
            }
        }
        location /status/ {
            api /status/;
            api_config_files on;
        }
        location =/p8s {
            prometheus all;
        }
        location /console/api/config/ {
            api /config/;
        }
        location /stats/ {
                api /status/http/server_zones/;
        }

**Comment by VBart** [comment]
Hi,

Have you configured a shared memory **zone** in your `upstream` blocks?

```nginx
upstream backend {
    zone backend 1m;
    ....
}
```

All metrics information is stored in shared memory zones, so it need to be configured for `upstream` blocks.

See in the docs
- https://angie.software/en/configuration/modules/http_api/#api-status-http-upstreams 
- https://angie.software/en/configuration/modules/http_upstream/#u-zone

**Comment by jointigers** [comment]
> Hi,
> 
> Have you configured a shared memory **zone** in your `upstream` blocks?
> 
> ```nginx
> upstream backend {
>     zone backend 1m;
>     ....
> }
> ```
> 
> All metrics information is stored in shared memory zones, so it need to be configured for `upstream` blocks.
> 
> See in the docs
> 
> * https://angie.software/en/configuration/modules/http_api/#api-status-http-upstreams
> * @ https://angie.software/en/configuration/modules/http_upstream/#u-zone






Hello, return error: curl http://ip:8080/status/http/upstreams/btc-prod-xpert

{
	"error": "PathNotFound",
	"description": "Requested API entity \"/status/http/upstreams/btc-prod-xpert\" doesn't exist."
}

 here is my configuration.


http {
    include       mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    proxy_cache_path /var/cache/angie/cache keys_zone=cache_zone:2m;
    limit_conn_zone $binary_remote_addr zone=limit_conn_zone:10m;
    limit_req_zone $binary_remote_addr zone=limit_req_zone:10m rate=1r/s;
resolver 127.0.0.53 status_zone=resolver_zone;
    include prometheus_all.conf;
    include vhosts/*.conf;
    include fullnode.upstream;
    include iplist.file;
    server {
        listen       8080;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
	location /console/ {
	    allow all;
	    alias /usr/share/angie-console-light/html/;
	    index index.html;
        location /console/api/ {
		 allow all;
	        api /status/;
	    }
	}
	location /status/ {
	    api /status/;
            api_config_files on;
	  allow all;
	}
	location =/p8s {
	    prometheus all;
	}
	location /console/api/config/ {
       	    api /config/;
	}
	location /stats/ {
    		api /status/http/server_zones/;
	}
location ~^/api/([^/]+)/(.*)$ {
    api /status/http/$1_zones/$2;
}
server {
        listen  80;
        server_name test.xxx.com;
        status_zone http_server_zone;
        proxy_cache cache_zone;
        location /status/ {
            api /status/;

            allow 127.0.0.1;
            allow all;
        }
    location /btcd/ {
            status_zone location_zone;
            limit_conn limit_conn_zone 1;
            limit_req zone=limit_req_zone burst=5;

    proxy_set_header Host $http_host;
    proxy_pass http://btc-prod-xpert/;
  }

upstream btc-prod-xpert {
  zone upstream 1m;
  server  47.76.67.8x:3000;
  server  47.76.219.8x:3000;
}





> Hi,
> 
> Have you configured a shared memory **zone** in your `upstream` blocks?
> 
> ```nginx
> upstream backend {
>     zone backend 1m;
>     ....
> }
> ```
> 
> All metrics information is stored in shared memory zones, so it need to be configured for `upstream` blocks.
> 
> See in the docs
> 
> * https://angie.software/en/configuration/modules/http_api/#api-status-http-upstreams
> * https://angie.software/en/configuration/modules/http_upstream/#u-zone

**Comment by jointigers** [comment]
Could you please provide the details for me to review?

**Comment by VBart** [comment]
Since you've closed the ticket, I guess your problem is resolved. Is it right?
