### ISSUE TITLE
Устаревшая версия modsecurity в документации

### ISSUE THREAD

**Issue by mikhailnov** [webserver-llc/angie#80]
На странице https://angie.software/configuration/modsecurity/ упоминается версия https://github.com/coreruleset/coreruleset 3.3.5

![image](https://github.com/webserver-llc/angie/assets/15802528/67f21111-c59c-4f11-af48-1c53f41b56a6)

Однако уже актуальная версия 4.х. Возникает вопрос, совместимы ли правила 4.х с модулем nginx 3.x, по т.к. версий 4.х модуля нет, то, наверное, совместимы.

**Comment by lonerr** [comment]
Мы попробуем исследовать вопрос совместимости и, при необходимости исправить пример в документации, спасибо.

**Comment by vkvj** [comment]
Здравствуйте.

Протестировали OWASP CRS v4.1.0 с Angie/1.5.0 - проблем совместимости не обнаружили.
В ближайшее время поправим документацию.
