### ISSUE TITLE
variable "XXX" is already declared in /etc/angie/http.d/xxx:10

### ISSUE THREAD

**Issue by agolodyaev** [webserver-llc/angie#84]
Привет.
После обновления angie-1.5.0-1.el9.x86_64 -> angie-1.5.0-2.el9.x86_64 сломался NJS

`Rocky Linux release 9.3 (Blue Onyx)

angie-1.5.0-2.el9
angie-module-njs-1.5.0-2.el9
`

`# angie -V
Angie version: Angie/1.5.0
nginx version: nginx/1.25.4
built with OpenSSL 3.0.7 1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/etc/angie --conf-path=/etc/angie/angie.conf --error-log-path=/var/log/angie/error.log --http-log-path=/var/log/angie/access.log --lock-path=/run/angie.lock --modules-path=/usr/lib/angie/modules --pid-path=/run/angie.pid --sbin-path=/usr/sbin/angie --http-acme-client-path=/var/lib/angie/acme --http-client-body-temp-path=/var/cache/angie/client_temp --http-fastcgi-temp-path=/var/cache/angie/fastcgi_temp --http-proxy-temp-path=/var/cache/angie/proxy_temp --http-scgi-temp-path=/var/cache/angie/scgi_temp --http-uwsgi-temp-path=/var/cache/angie/uwsgi_temp --user=angie --group=angie --with-file-aio --with-http_acme_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_mqtt_preread_module --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --feature-cache=../angie-feature-cache --with-ld-opt='-Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1'
`

Минимальный конфиг
`
load_module modules/ngx_http_js_module.so;
pid                     /run/angie.pid;

events {
    worker_connections  4096;
}

http {
    js_path      /var/www/njs/;
    js_import    js_logging_debug.js;
    include      /etc/angie/http.d/*.conf;

}

# configuration file /etc/angie/http.d/default.conf:
server {
    listen             80  default_server;
    server_name        first.server;
    js_set $js_request_headers  js_logging_debug.request_headers;
}

server {
    listen             80;
    server_name        second.server;
    js_set $js_request_headers  js_logging_debug.request_headers;
}
`

В логе получаю.
`angie: [emerg] variable "js_request_headers" is already declared in /etc/angie/http.d/default.conf:21`

**Comment by agolodyaev** [comment]
Я правильно понимаю, что теперь это нормальное поведение и js_set с одним именем может быть определён только однажды в независимости от контекста?
Syntax:	js_set $variable function | module.function;
Context:	http, server, location

**Comment by Ligature60** [comment]
Теперь это требование: js_set с одним именем может быть определён только однажды в независимости от контекста. Повторное объявление приводит к ошибке, которую вы наблюдаете.

**Comment by agolodyaev** [comment]
Понял. Спасибо за разъяснения.
