### ISSUE TITLE
how to enable quic like in old nginx-quic repository? 

### ISSUE THREAD

**Issue by osevan** [webserver-llc/angie#86]
Hey devs,

how i can enable quic like in old repository with
--with-http_v3_module
--with-stream_quic_module <–----- 

How to enable at configure level? 

Thanks and

Best regards

**Comment by VBart** [comment]
Support for QUIC in stream module was removed in nginx and that branch as well, see: https://hg.nginx.org/nginx/rev/113e2438dbd4

Could you explain the use case?

**Comment by osevan** [comment]
At the moment i thought every function is needed by http3.


.

**Comment by osevan** [comment]
I thought quic is for datagram http3.

Isnt it?

**Comment by osevan** [comment]
I want datagram socket instead of stream sockets

**Comment by VBart** [comment]
Stream module is for streaming L4 data, which can be datagram (UDP) or TCP.
For proxying HTTP/3 you can use QUIC + HTTP/3 support in the HTTP module.

**Comment by osevan** [comment]
Ok, thanks you very much.
