### ISSUE TITLE
Missing 499 status codes in prometheus metrics

### ISSUE THREAD

**Issue by soda-pop-ice-cream** [webserver-llc/angie#95]
Похоже что ответы 499 полностью игнорируются в метриках prometheus.
Я попробовал сгенерировать их 30 штук, все появились в логах, а в метриках пусто.

```
# HELP angie_http_location_zones_responses The number of responses with a specific status in an HTTP location zone.
# TYPE angie_http_location_zones_responses counter
angie_http_location_zones_responses{zone="bmo_metrics_api",code="200"} 2112811
angie_http_location_zones_responses{zone="bmo_metrics_api",code="400"} 77
angie_http_location_zones_responses{zone="bmo_metrics_api",code="404"} 1
angie_http_location_zones_responses{zone="bmo_metrics_api",code="500"} 16
angie_http_location_zones_responses{zone="bmo_metrics_api",code="502"} 11
```

**Comment by VBart** [comment]
Добрый день. Метрики ответов считают реальные ответы, т.е. то, что было отправлено клиенту.

`return 499` - это не ответ, а служебный внутренний код, который обрывает обработку запроса. Никаких ответов на такие запросы не отправляется.

Запросы, обработка которых была завершена без отправки ответа - считаются в метрике `discarded`.
Подробнее: https://angie.software/configuration/modules/http_api/#http-server-location

**Comment by soda-pop-ice-cream** [comment]
Спасибо, век живи - век учись :)
